name: Release

permissions:
  contents: write

on:
  # push:
  #   tags:
  #     - v[0-9]+.*
  push:
    branches: [main]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build
        # env:
        #   RUSTFLAGS: -C target-feature=+crt-static
        run: make build

      - name: Test
        run: make test

      - name: Debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPLOAD_URL=$(curl -s https://api.github.com/repos/plivox/sieve-parser/releases/tags/v0.1.2 | jq -r ".upload_url")

          if [[ "$UPLOAD_URL" != "" ]]; then
            UPLOAD_URL=${UPLOAD_URL/\{?name,label\}/}
          fi

          pushd target/release
            # tar caf sieve-parser-linux-x86_64-v0.1.2.zip LICENSE sieve-parser
            zip -9r sieve-parser-linux-x86_64-v0.1.2.zip LICENSE sieve-parser

            curl -X POST \
                  --data-binary @"sieve-parser-linux-x86_64-v0.1.2.zip" \
                  -H 'Content-Type: application/octet-stream' \
                  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                  "${UPLOAD_URL}?name=sieve-parser-linux-x86_64-v0.1.2.zip"
          popd

      # - uses: taiki-e/install-action@parse-changelog
      # - name: Generate Changelog
      #   run: parse-changelog header.md
