name: Release

permissions:
  contents: write

on:
  # push:
  #   tags:
  #     - v[0-9]+.*
  push:
    branches: [main]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build
        run: make build
        # env:
        #   RUSTFLAGS: -C target-feature=+crt-static

      - name: Test
        run: make test

      - uses: taiki-e/install-action@parse-changelog
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete --yes v0.1.2
          parse-changelog CHANGELOG.md 0.1.2 | gh release create v0.1.2 --title 0.1.2 --notes-file -

          pushd target/release
            # tar caf sieve-parser-linux-x86_64-v0.1.2.zip LICENSE sieve-parser
            zip -9r sieve-parser-linux-x86_64-v0.1.2.zip LICENSE sieve-parser
            
            gh release upload --clobber v0.1.2 sieve-parser-linux-x86_64-v0.1.2.zip
          popd

        # run: |
        #   UPLOAD_URL=$(curl -s https://api.github.com/repos/plivox/sieve-parser/releases/tags/v0.1.2 | jq -r ".upload_url")

        #   if [[ "$UPLOAD_URL" != "" ]]; then
        #     UPLOAD_URL=${UPLOAD_URL/\{?name,label\}/}
        #   fi

        #   pushd target/release
        #     # tar caf sieve-parser-linux-x86_64-v0.1.2.zip LICENSE sieve-parser
        #     zip -9r sieve-parser-linux-x86_64-v0.1.2.zip LICENSE sieve-parser

        #     gh release upload --clobber v0.1.2 sieve-parser-linux-x86_64-v0.1.2.zip
        #   popd

      # - uses: taiki-e/install-action@parse-changelog
      # - name: Generate Changelog
      #   run: parse-changelog header.md
